SEED_URLS = [
    # 5G / help
    # Vodafone Türkiye - 5G ana sayfa ve alt içerikler
    "https://www.vodafone.com.tr/5g",

    # Vodafone Türkiye - Cihazlar / telefonlar / ürün listeleme (son kullanıcı cihaz içerikleri)
    "https://www.vodafone.com.tr/cihazlar",
    "https://www.vodafone.com.tr/cihazlar/telefonlar",
    "https://www.vodafone.com.tr/cihazlar/iphone",
    "https://www.vodafone.com.tr/cihazlar/samsung",
    "https://www.vodafone.com.tr/cihazlar/xiaomi",
    "https://www.vodafone.com.tr/cihazlar/oppo",
    "https://www.vodafone.com.tr/cihazlar/huawei",
    "https://www.vodafone.com.tr/cihazlar/aksesuarlar",

    # Arama sayfası (site içi)
    "https://www.vodafone.com.tr/arama?q=5G",
    "https://www.vodafone.com.tr/arama?q=5g%20uyumlu",
    "https://www.vodafone.com.tr/arama?q=5g%20telefon",
    "https://www.vodafone.com.tr/arama?q=kapsama",
    "https://www.vodafone.com.tr/arama?q=h%C4%B1z%20testi",

    # Mağaza bulucu (son kullanıcı)
    "https://www.vodafone.com.tr/magaza-bul",

    # Yardım / destek (son kullanıcı destek süreçleri)
    "https://www.vodafone.com.tr/yardim",
    "https://www.vodafone.com.tr/yardim/sss",
    "https://www.vodafone.com.tr/yardim/cihaz",
    "https://www.vodafone.com.tr/yardim/internet",
    "https://www.vodafone.com.tr/yardim/hat-islemleri",
    "https://www.vodafone.com.tr/yardim/tarife",

    # Self servis / uygulama yönlendirmeleri
    "https://www.vodafone.com.tr/yanimda",

    # Genel kurumsal (az ama faydalı)
    "https://www.vodafone.com.tr/hakkimizda",

    "https://www.vodafone.com.tr/yardim/internet/5g",
    "https://www.vodafone.com.tr/yardim/internet/mobil-internet",
    "https://www.vodafone.com.tr/yardim/internet/hiz-testleri",

    # === Cihaz katalogları (scrape edilebilir) ===
    "https://www.vodafone.com.tr/faturaya-ek/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/vodafone-flex",
    "https://www.vodafone.com.tr/faturaya-ek/yenilenmis",
    "https://www.vodafone.com.tr/faturaya-ek/samsung-store",
    "https://www.vodafone.com.tr/faturaya-ek/apple-iphone-14-plus/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/apple-iphone-14/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/apple-iphone-15-plus/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/apple-iphone-15-pro-max/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/apple-iphone-15/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/apple-iphone-16-plus/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/apple-iphone-16-pro-max/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/apple-iphone-16-pro/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/apple-iphone-16/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/apple-iphone-16e/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/apple-iphone-17-pro-max/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/apple-iphone-17-pro/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/apple-iphone-17/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/apple-iphone-air/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/casper-via-a40/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/casper-via-m40/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/casper-via-m45/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/casper-via-x30-plus/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/casper-via-x30/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/casper-via-x40-8gb/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/casper-via-x45/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/general-mobile-era-30-4gb/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/general-mobile-era-30-pro/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/general-mobile-era-50-6gb/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/general-mobile-era-50-8gb/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/general-mobile-gm-24-pro/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/huawei-mate-x6/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/huawei-nova-12-se/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/huawei-nova-12s/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/huawei-nova-13/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/huawei-pura-70-pro/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/huawei-pura-70/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/iPhone-13/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/infinix-hot-60-pro/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/infinix-hot-60i-5g-4gb/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/infinix-hot-60i-5g-8gb/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/mipo-m17/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/mipo-m46-plus-8gb/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/mipo-m59-8gb/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/nubia-air-5g/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/nubia-focus-5g-6gb/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/nubia-neo-3-5g/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/nubia-neo-5g-8gb/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/nubia-v50-design-8gb/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/nubia-v70/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/oppo-a3-6gb/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/oppo-a38-6gb/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/oppo-a5-5g/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/oppo-a5-6gb/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/oppo-a5-8gb/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/oppo-a6-pro-5g/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/oppo-a60-8gb/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/oppo-reno-11f-5g-8gb/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/oppo-reno11-fs-8gb/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/oppo-reno13-f-5g/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/oppo-reno13-f/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/oppo-reno13-pro/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/oppo-reno14-5g/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/oppo-reno14-f-5g/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/oppo-reno14-pro-5g/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/realme-10/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/realme-12-8gb/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/realme-12-lite-8gb/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/realme-12-plus-5g-8gb/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/realme-c55/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/realme-c61-6gb/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/realme-c61-8gb/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/realme-c63-8gb/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/realme-c65-6gb/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/realme-c75-8gb/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/realme-note-60-4gb/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/realme-note-60-6gb/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/samsung-galaxy-a06/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/samsung-galaxy-a07/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/samsung-galaxy-a15-6gb/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/samsung-galaxy-a15/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/samsung-galaxy-a16-5g/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/samsung-galaxy-a16-8gb/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/samsung-galaxy-a16/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/samsung-galaxy-a17-5g/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/samsung-galaxy-a17/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/samsung-galaxy-a25-5g/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/samsung-galaxy-a26-5g-6gb/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/samsung-galaxy-a35/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/samsung-galaxy-a36-5g/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/samsung-galaxy-a54/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/samsung-galaxy-a55/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/samsung-galaxy-a56-5g/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/samsung-galaxy-s23/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/samsung-galaxy-s24-fe/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/samsung-galaxy-s24-plus/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/samsung-galaxy-s24-ultra/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/samsung-galaxy-s24/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/samsung-galaxy-s25-5g/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/samsung-galaxy-s25-fe-5g/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/samsung-galaxy-s25-plus-5g/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/samsung-galaxy-s25-ultra-5g/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/samsung-galaxy-z-flip-6-12gb/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/samsung-galaxy-z-flip7-5g/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/samsung-galaxy-z-flip7-fe-5g/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/samsung-galaxy-z-fold-6-12gb/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/samsung-galaxy-z-fold-6/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/samsung-galaxy-z-fold7-5g/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/tcl-onetouch-4042s/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/tcl-onetouch-5041/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/tecno-camon-30-12gb/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/tecno-camon-30-5g-12gb/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/tecno-camon-30-pro-5g-12gb/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/tecno-camon-40-premier-5g/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/tecno-camon-40-pro-5g/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/tecno-camon-40/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/tecno-phantom-v-fold-2/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/tecno-spark-20-pro/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/tecno-spark-20/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/tecno-spark-20c-8gb/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/tecno-spark-30-pro/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/tecno-spark-30/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/tecno-spark-30c/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/tecno-spark-40-5g/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/tecno-spark-40-pro/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/tecno-spark-40/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/tecno-spark-40c/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/tecno-spark-slim-5g/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/vivo-v30-lite-8gb/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/vivo-v50-lite-5g/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/vivo-v50-lite/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/vivo-y18-8gb/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/vivo-y19s-4gb/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/vivo-y19s-8gb/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/vivo-y28-8gb/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/vivo-y29/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/vivo-y29s-5g/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/xiaomi-redmi-13-8gb/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/xiaomi-redmi-13c-6gb/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/xiaomi-redmi-13c/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/xiaomi-redmi-14c/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/xiaomi-redmi-15-5g/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/xiaomi-redmi-15/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/xiaomi-redmi-15c-5g/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/xiaomi-redmi-15c-8gb/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/xiaomi-redmi-note-12-8gb/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/xiaomi-redmi-note-13-pro/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/xiaomi-redmi-note-13/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/xiaomi-redmi-note-14-5g/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/xiaomi-redmi-note-14-pro-5g/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/xiaomi-redmi-note-14-pro-8gb/p/telefonlar",
    "https://www.vodafone.com.tr/faturaya-ek/xiaomi-redmi-note-14/p/telefonlar"
]

CATALOG_URL = "https://www.vodafone.com.tr/faturaya-ek/telefonlar"
ALLOWED_DOMAINS = {"www.vodafone.com.tr"}